name: 'Terraform'

on:
  push:

jobs:

  terraform:

    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}


    - name: Terraform Init
      run: terraform init
      env:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACESSKEY }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
             AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}


    - name: Terraform Plan
      env:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACESSKEY }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
             AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      run: terraform plan

    - name: Terraform Apply
      env:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACESSKEY }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
             AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -destroy --auto-approve
